hostname = "127.0.0.1"
port = 8199
template_path = "templates"
csrf_key = "We spent so much time chasing suns, we lost sight..."

[tls]
private_key = "notgull.rsa"
public_key = "notgull.pem"

[urls]
api_url = "https://localhost:8199/api"
static_url = "http://localhost:4566/notgull"
auth_url = "http://test.test/auth"
