hostname = "127.0.0.1"
port = 8199
http_port = 8198
template_path = "templates"
favicon_path = "favicon.ico"
csrf_key = "We spent so much time chasing suns, we lost sight..."

[tls]
private_key = "notgull.rsa"
public_key = "notgull.pem"

[urls]
api_url = "https://127.0.0.1:8199/api"
static_url = "http://127.0.0.1:4566/notgull"
auth_url = "http://test.test/auth"
web_url = "https://127.0.0.1:8199"

[oauth2]
client_id = "ndndotnet"
client_secret = "ndndotsecret"
auth_url = "http://127.0.0.1:4444/oauth2/auth"
token_url = "http://127.0.0.1:4444/oauth2/token"
redirect_url = "https://127.0.0.1:8199/callback"

[frontpage_map]
about_me = { path = "templates/about_me.md", name = "About Me" }
contact_me = { path = "templates/contact_me.md", name = "Contact Info" }

[s3]
bucket_name = "notgull"
endpoint_url = "http://localhost:4566"
region = "us-west-1"