hostname = "127.0.0.1"
port = 8200
key_path = "notgull-auth.rsa"
cert_path = "notgull-auth.pem"

[verify]
client_id = "notgull.net"
client_secret = "ChasingSuns123"
redirect_uri = "https://localhost:8199/login"

[urls]
base_url = "https://localhost:8200"